// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706461075);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1706464675);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1706461075);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1706461075);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f002d371-4ba1-4607-97dd-97e8528ad70c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1706461047853");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1706482647853");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1706461045");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1706461045);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("captivedetect.canonicalURL", "");
user_pref("devtools.console.stdout.chrome", false);
user_pref("devtools.debugger.remote-enabled", false);
user_pref("devtools.everOpened", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.iniFile.exists.appversion", "122.0-1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("doh-rollout.provider-list", "[{\"UIName\":\"Mozilla Cloudflare\",\"uri\":\"https://mozilla.cloudflare-dns.com/dns-query\"},{\"UIName\":\"Quad9\",\"uri\":\"https://dns.quad9.net/dns-query\"}]");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9c049eceb01049c889d431f9f1384028");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706461075);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240123225120");
user_pref("extensions.lastAppVersion", "122.0-1");
user_pref("extensions.lastPlatformVersion", "122.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"22af7b2a-b7f6-48d1-bfeb-1443de3806e1\",\"pictureinpicture@mozilla.org\":\"cf4dde97-293a-41e6-a292-0211bd10ebf9\",\"screenshots@mozilla.org\":\"20920824-7299-49b9-a88f-86892e476ffd\",\"webcompat@mozilla.org\":\"ce1ff97f-96f0-4f0a-8970-fb91e48144dd\",\"default-theme@mozilla.org\":\"ed7fb71a-ecce-4cf0-9ef9-5425c8b1c079\",\"addons-search-detection@mozilla.com\":\"66c00673-8df4-4196-ba1d-07fc2a913f34\",\"wikipedia@search.mozilla.org\":\"0d0dbcc7-daa9-472b-9393-89a0034727cd\",\"ddg@search.mozilla.org\":\"8f384675-2d8d-4ce4-8fb4-aaa3b11dd157\",\"uBlock0@raymondhill.net\":\"57ea3041-c9b0-481f-ba6d-f5518596e3a7\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1706461247);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20240123225120");
user_pref("media.gmp-manager.lastCheck", 1706461085);
user_pref("media.gmp-manager.lastEmptyCheck", 1706461085);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.delegation.enabled", false);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("places.database.lastMaintenance", 1706461247);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.fingerprintingProtection", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.emailtracking.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "7b0f1340-2640-4ba9-94af-d8590f61a0dd");
user_pref("security.tls.enable_0rtt_data", false);
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1706461247);
user_pref("toolkit.startup.last_success", 1706461044);
user_pref("toolkit.telemetry.cachedClientID", "be0a432d-ed61-4874-988c-ce043593981a");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.winRegisterApplicationRestart", false);
user_pref("webchannel.allowObject.urlWhitelist", "");
