$mainMod = SUPER
#Applications
bind = $mainMod,t,       exec, alacritty
bind = $mainMod,B,       exec, blueberry
bind = $mainMod CTRL,L,  exec, swaylock
bind = $mainMod,N,       exec, librewolf
bind = $mainMod,SPACE,   exec, ~/.config/hypr/scripts/launcher
bind = $mainMod,P,       togglefloating 
bind = $mainMod,Q,       killactive
bind = $mainMod,M,       exit
bind = ,Print,           exec, ~/.config/hypr/scripts/screenshot
bind = $mainMod,G,       exec, ~/.config/hypr/scripts/togglefloat

#Workspaces
bind = $mainMod,H,movefocus,l
bind = $mainMod,J,movefocus,d
bind = $mainMod,K,movefocus,u
bind = $mainMod,L,movefocus,r

# bind = CTRL,1,workspace,1
# bind = CTRL,2,workspace,2
# bind = CTRL,3,workspace,3
# bind = CTRL,4,workspace,4
# bind = CTRL,5,workspace,5
# bind = CTRL,6,workspace,6
bind = $mainMod,1,workspace,1
bind = $mainMod,2,workspace,2
bind = $mainMod,3,workspace,3
bind = $mainMod,4,workspace,4
bind = $mainMod,5,workspace,5
bind = $mainMod,6,workspace,6
bind = $mainMod,7,workspace,7
bind = $mainMod,8,workspace,8
bind = $mainMod,9,workspace,9
bind = $mainMod,0,workspace,10

bind = $mainMod ALT,1,movetoworkspace,1
bind = $mainMod ALT,2,movetoworkspace,2
bind = $mainMod ALT,3,movetoworkspace,3
bind = $mainMod ALT,4,movetoworkspace,4
bind = $mainMod ALT,5,movetoworkspace,5
bind = $mainMod ALT,6,movetoworkspace,6
bind = $mainMod ALT,7,movetoworkspace,7
bind = $mainMod ALT,8,movetoworkspace,8
bind = $mainMod ALT,9,movetoworkspace,9
bind = $mainMod ALT,0,movetoworkspace,10

bind = $mainMod SHIFT,D,workspace,e+1
bind = $mainMod SHIFT,A,workspace,e-1

bind = $mainMod SHIFT,L,workspace,e+1
bind = $mainMod SHIFT,H,workspace,e-1

bind = $mainMod ALT, H, movewindow, l
bind = $mainMod ALT, J, movewindow, d 
bind = $mainMod ALT, K, movewindow, u
bind = $mainMod ALT, L, movewindow, r

#Media Buttons
bindl=, XF86AudioRaiseVolume, exec, pamixer -ui 5
bindl=, XF86AudioLowerVolume, exec, pamixer -ud 5
bindl=, XF86AudioMute, exec,pamixer --toggle-mute

bindle=, XF86MonBrightnessUp, exec, brightnessctl set 10%+
bindle=, XF86MonBrightnessDown, exec, brightnessctl set 10%-

bindl=, XF86AudioPlay, exec, playerctl play-pause 
bindl=, XF86AudioNext, exec, playerctl next
bindl=, XF86AudioPrev, exec, playerctl previous

