
[colors.primary]
    background= '0x1f211b'
    foreground= '0xd4bf98'
[colors.normal]
    black=   '0x282828'
    red=     '0xea6962'
    green=   '0xa9b665'
    yellow=  '0xd8a657'
    blue=    '0x7daea3'
    magenta= '0xd3869b'
    cyan=    '0x89b482'
    white=   '0x7a6f64'

[colors.bright]
    black=   '0x5f5a60'
    red=     '0xea6962'
    green=   '0xa9b665'
    yellow=  '0xd8a657'
    blue=    '0x7daea3'
    magenta= '0xd3869b'
    cyan=    '0x89b482'
    white=   '0xddc7a1'

